# 应用服务 WEB 访问端口
server:
  port: 18610

# THYMELEAF (ThymeleafAutoConfiguration)
spring:
  thymeleaf:
    cache: false # 开启模板缓存（默认值： true ）
    check-template: true # 检查模板是否存在，然后再呈现
    check-template-location: false # 检查模板位置是否正确（默认值 :true ）
    servlet:
      content-type: text/html #Content-Type 的值（默认值： text/html ）
    enabled: true # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    mode: HTML # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML)
    encoding: UTF-8 # 模板编码
    excluded-view-names: # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    prefix: classpath:/templates/ # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    suffix: .html # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
